---
title: "Capstone Proposal"
author: "Donnie Meyer"
date: "October 1, 2018"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Project Proposal

#### What is the problem you want to solve?

I want to understand which factors influence households who have **considered** or are currently **considering** roof top solar, to actually make the switch and **adopt** roof top solar. Perhaps and more importantly, what factors lead households who considered adopting roof top solar to reconsider and not take up adoption. There are many reasons why consumers adopt, and choose not to rooftop adopt solar. For example, some adopt for financial gain while others adopt for environmental reasons. On the other hand its likley consideres of roof top solar do not take up adoption because the upfront cost is not finacially viable. Understanding the roof top solar adoption characteristics of consumers seems to be an extremely worth while en-devour. Volatile energy prices, climate change, and lack of jobs in traditional energy sectors such as the coal industry etc. are all problems that could be alleviated with an increase in roof top solar adoption. 

#### Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?

I believe solar installation firms would be interested in this information as it would help them pinpoint marketing strategies to increase sales. Knowing which groups of consumers to target with advertising etc. could ultimately encourage the adoption of rooftop solar. I also believe governments and policy makers at all levels would find value in understanding the reasons why consumers adopt solar while others do not. It could be that many consumers have considered solar and would like to adopt but lack the financial resources to do so. This would allow policy makers to craft more effective incentive based policies and allow these households more resources to take up adoption. Last but not least, if climate change is as serious a threat as the majority of climate scientists claim it is, then society as a whole would most likely benefit most from an increase in rooftop solar adoption. Roof top solar technologies would allow households to reduce their fossil fuel energy consumption. 

#### What data are you going to use for this? How will you acquire this data?

The data I will be using is a survey data set where all features are categorical, i.e no continuous variables. The name of the data set is "Understanding the Evolution of Customer Motivations and Adoption Barriers in Residential Solar Markets: Survey Data" and it has been made public from the National Renewable Energy Laboratory (NREL). 

The data comprises of three surveys, an adopter survey, a considerer survey, and a general population survey. The adopter survey is limited to households who have adopted roof top solar, the consider survey is limited to households who have seriously considered adopting solar but have yet to do so, and the general population survey is limited to households who have not adopted roof top solar. The surveys were conducted in the four US states California, Arizona, New York, and New Jersey.

#### In brief, outline your approach to solving this problem (knowing that this might change later).

The analysis of catagorical data must be approached in a different fashion than continuous data. Statistics such the mean and standard deviation cannot be computed and models such as linear regression are not useful. Luckily there are a range of statistcial techniques such as mode and median and models such as logistic regression that have been developed to analyze catagorical data and survey data. 

The data wrangling process will included importing the data into R and analyzing it for missing values, recoding assignments, and features useful for the analysis. The next step will be to plot and visulize the data to gain a more intutitive understanding of the relationships between the dependent variable and the independent variables. There are many interesting ways to visulize catagorical data that I hope to explore. In addition to ploting/visulizing the data contingency will be created to tabulate and explore the data. Statistical tests such as the Pearsons chis quared test and the fishers exact test can be used to test the independence between groups and their responses to the survey questions.

The survey data set has many explanatory variables that may be useful for developing a model. I currently have a binary dependent variable called "HAVESOLAR" in the adopter and considerer data sets. If I append these two data sets the variable is equal to 1 for adopted solar, and equal to 0 if they currently hav not adopted solar. I will use a logistic regression to determine which factors play a statistically significant role in solar adoption. A full logistic regression analysis will be conducted such model diagnostiocs, confussion matrix, etc. The model will predict which households have adopted solar and identify which factors played a prominent role in the process from considering solar to adopting solar. 

If time permits I would like to perform a clustering algorithm on the data set. Becasue the data is catagorical kmeans clustering will not work. I have discovered a similar clustering algorithm that uses the mode as opposed to the mean called k-modes clustering. 

#### What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.

The deliverables will be a written report in rmarkdown in addition to slides for presentation or a blog posting on wordpress. Code will be available through github. 
